### ISSUE TITLE
Android MCrypt decode Invalid int

### ISSUE THREAD

**Issue by omatt** [serpro/Android-PHP-Encrypt-Decrypt#13]
Currently testing encrypt-decrypt functions for Android side.

Plain text is "You should be able to read this, bro."
iv = 483e705e5a7f270f;
secretKey = 53c7a330f1bf93d6;

encrypt output is "j:Xg֎	�T;�H��ZA����7�(�yJ1$([d{�$�����ûD"
decrypt gives out an error: java.lang.Exception: [decrypt] Invalid int: "j:"

**Comment by FloridaStream** [comment]
try 
```
iv = "483e705e5a7f270f";
secretKey = "53c7a330f1bf93d6";
```

**Comment by omatt** [comment]
Those are the same values. iv and secretKey are String.

**Comment by omatt** [comment]
fixed it by using bytesToHex
