### ISSUE TITLE
Alternative for Ionic 2 Framework

### ISSUE THREAD

**Issue by SachetBajra** [serpro/Android-PHP-Encrypt-Decrypt#17]
I implemented this method in Android and PHP. But now after creating the same app in Ionic 2 for iOS need to perform the same process in ionic 2 (typescript). Any help would be wonderful.

**Comment by serpro** [comment]
I've never worked with TypeScript, but I found this code that might help you:
https://github.com/PasteSafe/pastesafe/blob/master/src/pastesafe.ts

**Comment by SachetBajra** [comment]
I managed to do it. 

https://github.com/SachetBajra/IonicFramework_v2/wiki/AES-Encryption-in-Ionic-Framework-2
