### ISSUE TITLE
Problem integrating it on Android

### ISSUE THREAD

**Issue by miranos** [serpro/Android-PHP-Encrypt-Decrypt#19]
Hi
When i try to do this:

```
import com.myproject.MCrypt;

MCrypt mcrypt = new MCrypt();
String decrypting = new String(mcrypt.decrypt(myencryptedtext));
```

Java ask me to add exception:
```
        MCrypt mcrypt = new MCrypt();
        try {
            String decrypting = new String(mcrypt.decrypt(myencryptedtext));
            Log.w("decrypting", decrypting );
        } catch (Exception e) {

        }
```

But nothing returned in the LOGS !

Can you help me please ?

**Comment by MeTaXaS4** [comment]
try {
            String decrypting = new String(mcrypt.decrypt(myencryptedtext));
            Log.w("decrypting", decrypting );
        } catch (Exception e) {
 Log.e("decrypting", e.getMessage());
        }

**Comment by miranos** [comment]
Already did that sir, but no error message nor the decrypted data shown !

**Comment by MeTaXaS4** [comment]
but on your code you don't have anything on catch... are you sure that "Already did that sir, but no error message nor the decrypted data shown !" ?

**Comment by miranos** [comment]
I added your code there sir ! is what i said:

` Log.e("decrypting", e.getMessage());`

**Comment by MeTaXaS4** [comment]
add a breakpoint then and check again.

**Comment by miranos** [comment]
Just missed a dot somewhere, thank you for the help, issue solved.

**Comment by serpro** [comment]
Thanks @MeTaXaS4.

I'm glad your issue is solved @miranos
