### ISSUE TITLE
Json Decryption

### ISSUE THREAD

**Issue by Robokishan** [serpro/Android-PHP-Encrypt-Decrypt#20]
java.lang.Exception: [decrypt] Invalid int: "{ "

i am getting this error how to resolve it ?

**Comment by serpro** [comment]
Can you add your code here to check it?

**Comment by Robokishan** [comment]
i am Very Very sorry it was My mistake in java 
i did not create it using new string , i just use string.valueof(mcrypt.decrpt) ,
i am very very sorry
this code is great help me lot
