### ISSUE TITLE
Security "Crypto" provider deprecated in Android N

### ISSUE THREAD

**Issue by sudarshan103** [serpro/Android-PHP-Encrypt-Decrypt#21]
https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html
The deprecation affects this logic, right ?

**Comment by serpro** [comment]
Thanks for the link, it's interesting. I guess the code will need some refactoring.

**Comment by MeTaXaS4** [comment]
@serpro if you need any help with that let me know, i would like to help you with your lib that is very helpful

**Comment by serpro** [comment]
Thanks @MeTaXaS4 
Feel free to submit any Pull Request you make. That's the best thing about open source projects :+1:

**Comment by MeTaXaS4** [comment]
after further reading of post and your code, the lib doesn't have any problem.

**Comment by serpro** [comment]
Hi @MeTaXaS4,

That's true. I thought they were deprecating Crypto provider.But they are only deprecating that algorithm.

Thanks. 
I'll close this issue.
