### ISSUE TITLE
Objective C equivalent for this.

### ISSUE THREAD

**Issue by jayaryan** [serpro/Android-PHP-Encrypt-Decrypt#24]
I want to use this in my PHP server side API and in Android App and iOS app.
Working fine with the above code in PHP and Android.

Now need full code for the iOS equivalent for this. Can anyone have this.. please

**Comment by serpro** [comment]
See this: https://github.com/serpro/Android-PHP-Encrypt-Decrypt/issues/25#issuecomment-601681532
