### ISSUE TITLE
Alternative solution for iOS swift

### ISSUE THREAD

**Issue by Bhautik07** [serpro/Android-PHP-Encrypt-Decrypt#28]

**Comment by kishanbarmawala** [comment]
Use this pod: -
https://github.com/krzyzanowskim/CryptoSwift/tree/swift32


extension String {
    func aes_Encrypt() -> String {
        let key = "0123456789abcdef"
        let iv = "fedcba9876543210"
        var result = ""
        do {
            let aes = try! AES(key: key, iv: iv, padding: Padding.zeroPadding)
            let encrypted = try aes.encrypt(Array(self.utf8))
            result = encrypted.toHexString()
        } catch {
            print(error)
        }
        return result
    }
}

// Use:-

let str = // YOUR STRING
            
let result = str.aes_Encrypt()   // "result" is your encrypted string

**Comment by kiishanbarmawala** [comment]
> _No description provided._

Use this pod: -
https://github.com/krzyzanowskim/CryptoSwift/tree/swift32


extension String {
    func aes_Encrypt() -> String {
        let key = "0123456789abcdef"
        let iv = "fedcba9876543210"
        var result = ""
        do {
            let aes = try! AES(key: key, iv: iv, padding: Padding.zeroPadding)
            let encrypted = try aes.encrypt(Array(self.utf8))
            result = encrypted.toHexString()
        } catch {
            print(error)
        }
        return result
    }
}

// Use:-

let str = // YOUR STRING
            
let result = str.aes_Encrypt()   // "result" is your encrypted string
