### ISSUE TITLE
doesn work for Video

### ISSUE THREAD

**Issue by mubasshir** [serpro/Android-PHP-Encrypt-Decrypt#9]
Hi, I need to use this API, but before use, I just did plain test, where PHP encryption decryption worked for txt, docx etc but when it comes to video, it fails. I also noticed there initial space was erased, trim removes it.

**Comment by agp94** [comment]
How did you use with docx?

**Comment by mubasshir** [comment]
just read your content using file_get_contents and base64encode it

BTW, i dropped this plugin as there was no response and implemented my own

**Comment by serpro** [comment]
Hi @mubasshir sorry I didn't reply earlier. I haven't had much time lately to update the code. If you know any improvements, feel free to submit pull request.

Thanks. @agp94 I haven't tried with docx files. Maybe you can try base64 encode it.. and then encrypt
